### Use a extensão do VSCode - REST Client (Huachao Mao)

GET http://localhost:8080/users

###

GET http://localhost:8080/user/5634d43e-b49c-4d73-909d-38907f6f674a

###

POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "name": "User RMS",
    "email": "rms@localhost.com",
    "password": "1234"
}

###

PUT http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "id": "83c957bd-f0be-4b87-b3a0-0873b96b3175",
    "name": "User RMS",
    "email": "rms@app.com",
    "password": "123456789"
}

###

DELETE http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "id": "b910c8aa-a586-4a3c-8caf-4663e4d2f4a6"
}